from enum import Enum

class Role(str, Enum):
    ENGINEER = "ENGINEER"
    TECH_LEAD = "TECH_LEAD"
    OPS_REVIEWER = "OPS_REVIEWER"
    SECURITY_REVIEWER = "SECURITY_REVIEWER"
    ADMIN = "ADMIN"

class Permission(str, Enum):
    CREATE_CHANGE = "CREATE_CHANGE"
    REVIEW_TECH = "REVIEW_TECH"
    REVIEW_OPS = "REVIEW_OPS"
    REVIEW_SECURITY = "REVIEW_SECURITY"
    MANAGE_USERS = "MANAGE_USERS"
    VIEW_ALL = "VIEW_ALL"
    CANCEL_ANY = "CANCEL_ANY"