from enum import Enum


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ChangeStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    TECH_REVIEW = "TECH_REVIEW"
    OPS_REVIEW = "OPS_REVIEW"
    SECURITY_REVIEW = "SECURITY_REVIEW"
    APPROVED = "APPROVED"
    SCHEDULED = "SCHEDULED"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    CANCELLED = "CANCELLED"
class Role(str, Enum):
    ENGINEER = "ENGINEER"
    TECH_LEAD = "TECH_LEAD"
    OPS_REVIEWER = "OPS_REVIEWER"
    SECURITY_REVIEWER = "SECURITY_REVIEWER"
    ADMIN = "ADMIN"

class Permission(str, Enum):
    CREATE_CHANGE = "CREATE_CHANGE"
    REVIEW_TECH = "REVIEW_TECH"
    REVIEW_OPS = "REVIEW_OPS"
    REVIEW_SECURITY = "REVIEW_SECURITY"
    MANAGE_USERS = "MANAGE_USERS"
    VIEW_ALL = "VIEW_ALL"
    CANCEL_ANY = "CANCEL_ANY"
